name: Publish to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - "release"
      - "versions/*"
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      
      
jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/node.js.yml
  publish:
    runs-on: ubuntu-24.04-arm
    needs: [run-tests]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GHCR
        env: 
          REGISTRY: ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata for Docker GHCR
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-') }}
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=semver,pattern={{major}}.{{minor}}
          # disable automatic latest tag
          flavor: |
            latest=false
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
